Algoritmo "Exercicio05"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 28/08/2026
Var
// Seção de Declarações das variáveis 
numero:inteiro
antecessor: inteiro
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Escreval("Programa Antecessor")
Escreval("Digite um número :")
Leia(numero)
antecessor<- numero -1
Escreval("O antecessor do número digitado é : ",antecessor)

Fimalgoritmo