Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 31/08/2026
Var
// Seção de Declarações das variáveis 
metros:real;
conversao:real;

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Escreval("Digite os metros para converte-lo em centímentros ")
Escreva("Digite os metros: ")
leia(metros)
conversao<-metros*100
Escreval("A conversão em centímetros é de: ",conversao)

Fimalgoritmo