Algoritmo "Exercicio01"

// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 16/09/2026
Var
// Seção de Declarações das variáveis 
tempCelsius, tempFarenheit: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Escreval("Converta uma temperatura de Celsius para Farenheit. ")
Escreva("Digite a temperatura em Cesius: ")
leia(tempCelsius)

tempFarenheit<- (9 * tempCelsius + 160) / 5
Escreva("A temperatura convertida é de: ", tempFarenheit)

Fimalgoritmo