Algoritmo "Exercicio13"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   :  custo de um carro novo ao consumidor é a soma do custo de fábrica com a porcentagem do
//distribuidor e dos impostos (aplicados ao custo de fábrica). Supondo que o percentual do distribuidor
//seja de 28% e os impostos de 45%, escrever um algoritmo para ler o custo de fábrica de um carro,
//calcular e escrever o custo final ao consumidor.
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 02/09/2026
Var
// Seção de Declarações das variáveis 
custoFabricaImposto:real;
porcentagemDistribuicao: real;
imposto:real;
valorFinal: real;

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Escreval("ExercÍcio 13 Faccat ")

porcentagemDistribuicao<- (28 * 100) /valorFinal
imposto< (45 * 100) / valorFinal
valorFinal<- custoFabricaImposto + porcentagemDistribuicao


Escreva ("O valor final do carro é de: ", valorFinal )

Fimalgoritmo
 custo de um carro novo ao consumidor é a soma do custo de fábrica com
 a porcentagem do
distribuidor e dos impostos (aplicados ao custo de fábrica).
Supondo que o percentual do distribuidor
seja de 28% e os impostos de 45%, escrever um algoritmo para ler o custo
de fábrica de um carro,
calcular e escrever o custo final ao consumidor.