Algoritmo "Exercicio35"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 11/09/2026
Var
// Seção de Declarações das variáveis 
numero:real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Escreval("Descobrir se um valor é positivo, negativo ou zero")
Escreva("Digite um número: ")
leia(numero)

se numero=0 entao
Escreva ("O número é igual a zero. ")
senao
se numero<0 entao
Escreval("O número é negativo. ")
senao
se numero>0 entao
Escreva("O número é positivo. ")
fimse
fimse
fimse
Fimalgoritmo