Algoritmo "ExercicioAula5"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 10/09/2026
Var
// Seção de Declarações das variáveis
contadora, acumuladora:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...

   acumuladora <- 1


   enquanto contadora <= 101 faca
      acumuladora <- acumuladora + contadora

      escreva("O contador é: ", contadora, " | A soma atual é: ", acumuladora)
      escreval()

      contadora <- contadora + 1
   fimenquanto


Fimalgoritmo