Algoritmo "Exercicio64"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 22/09/2026
Var
// Seção de Declarações das variáveis 
celsius, fahrenheit: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
celsius <- 10

enquanto celsius <= 100 faca

fahrenheit <- (9 * celsius + 160) / 5

escreval("Celsius: ", celsius, " | Fahrenheit: ", fahrenheit)

celsius <- celsius + 10
fimenquanto

Fimalgoritmo