Algoritmo "Exercicio63"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 22/09/2026
Var
// Seção de Declarações das variáveis 
termo1, termo2, proximo, contador: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
termo1 <- 1
termo2 <- 1
contador <- 1

enquanto contador <= 15 faca

escreval(termo1)

proximo <- termo1 + termo2
termo1 <- termo2
termo2 <- proximo

contador <- contador + 1
fimenquanto

Fimalgoritmo