Algoritmo "ExercicioEstruturaDeEscolha"
// Disciplina   : [Linguagem e Lógica de Programação com JavaScript]
// Professor   : Jailson
// Autor(a)    : Larissa Fernandes Coelho
// Data atual  : 03/09/2026
Var
// Seção de Declarações das variáveis
diaDaSemana:inteiro;

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
Escreval("Digite um número e descubra o dia da semana ")
leia(diaDaSemana)

escolha diaDaSemana
caso 1
Escreval("Domingo")
caso 2
Escreval("Segunda-Feira")
caso 3
Escreval("Terça-Feira")
caso 4
Escreval("Quarta-Feira")
caso 5
Escreval ("Quinta-Feira")
caso 6
Escreval ("Sexta-Feira")
caso 7
Escreval("Sábado")
outrocaso
Escreva("Dia da semana não existênte ")
fimescolha

Fimalgoritmo