Algoritmo "Exercicio22"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 09/09/2026
Var
// Seção de Declarações das variáveis 
numero:real;

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Escreval("Descubra se um número é maior ou menor que 10! ")
Escreva("Digite um número: ")
leia(numero)

se numero <10 entao
Escreval("O número é menor que 10. ")
senao
se numero= 10 entao
Escreval("O número é igual a 10. ")
senao
se numero>10 entao
Escreval ("O número é maior que 10. ")
fimse
fimse
fimse
Fimalgoritmo