Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 28/08/2026
Var
// Seção de Declarações das variáveis 
numero01:inteiro;
numero02:inteiro;
sub:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Escreval("Subtração de números: ")
Escreval("Digite o 1°número: ")
leia(numero01)
Escreval("Digite o 2°número: ")
leia(numero02)
sub<-numero01-numero02
Escreval("O resultado é de: ", sub)

Fimalgoritmo