Algoritmo "Exercicio58"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 22/09/2026
Var
// Seção de Declarações das variáveis 
i, soma: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
i <- 1
soma <- 0

enquanto i <= 100 faca
soma <- soma + i
i <- i + 1
fimenquanto
escreval("A soma dos 100 primeiros numeros inteiros e: ", soma)

Fimalgoritmo