Algoritmo "ExercicioAulas"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 10/09/2026
Var
// Seção de Declarações das variáveis
contador:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
enquanto contador<10 faca
escreval("Pão de Queijo")
contador<- contador +1
fimenquanto

Fimalgoritmo