Algoritmo "Exercicio65"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 22/09/2026
Var
// Seção de Declarações das variáveis 
valor, soma, media: real
contador: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
soma <- 0
contador <- 1

enquanto contador <= 10 faca

escreva("Digite o ", contador, "o valor: ")
leia(valor)

soma <- soma + valor
contador <- contador + 1
fimenquanto

media <- soma / 10

escreval("Somatorio: ", soma)
escreval("Media aritmetica: ", media)

Fimalgoritmo