Algoritmo "Exercicio15"
// Disciplina   : [Linguagem e Lógica de Programação com JavaScript]
// Professor   : Jailson
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Larissa Fernandes Coelho
// Data atual  : 03/09/2026
Var
// Seção de Declarações das variáveis
fahrenheit:real;
conversao:real;
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
Escreval("Conversão de Fahrenheit para Celsius ")
Escreval("Digite o valor em Fahrenheit: ")
leia(fahrenheit)

conversao<- (fahrenheit - 32) / 1.8

Escreval("O valor em Celsius é de: ",conversao,"°C")

Fimalgoritmo