Algoritmo "Exercicio15Faccat"
// Disciplina  : [Lógica de Programação com JavaScript]
// Professor   : Jailson Costa dos Santos
// Descrição   : Ler um valor e escrever a mensagem É MAIOR QUE
// 10! se o valor lido for maior que 10, caso contrário escrever
// NÃO É MAIOR QUE 10!
// Autor(a)    : Jailson
// Data atual  : 02/09/2026
Var
   // Seção de Declarações das variáveis
   numero: inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   Escreval("Exercicio 14 Faccat")
   Escreval("Digite um número :")
   Leia(numero)
   se numero <0 entao
      Escreval("Número digitado é negativo. ")
   senao
      Escreval("Número digitado é positivo. ")
   fimse

Fimalgoritmo