Algoritmo "Exercicio07"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 28/08/2026
Var
// Seção de Declarações das variáveis 
base:real
altura:real
resultado:real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Escreva("Calcule a base e a altura de um retângulo ")
Escreval("Qual o valor da base do retângulo? ")
leia(base)
Escreval("Qual o valor da altura do retângulo? ")
leia(altura)
resultado<-base*altura
Escreval("O resultado é de: ", resultado)

Fimalgoritmo