Algoritmo "Exercicio69"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Apresentar os quadrados dos números inteiros de 15 a 200
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 23/09/2026
Var
// Seção de Declarações das variáveis 
numero, quadrado:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
numero<-15
repita
quadrado <- numero * numero
escreval(quadrado)
numero<- numero + 1
ate numero<= 200


Fimalgoritmo