Algoritmo "Exercicio03"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 16/09/2026
Var
// Seção de Declarações das variáveis 
volume,raio,altura: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Escreval("Descubra o valor do volume de uma lata de óleo. ")
Escreva("Digite o raio da lata: ")
leia(raio)
Escreva("Digite a altura: ")
leia(altura)

volume<- 3.14 * raio^2 * altura

Escreval("O valor do volume da lata de óleo é de: ",volume)

Fimalgoritmo
