Algoritmo "Exercicio79"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 27/09/2026
Var
// Seção de Declarações das variáveis 
numero, quadrado: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
para numero de 15 ate 200 faca
quadrado <- numero * numero
escreval(numero, " ao quadrado = ", quadrado)
fimpara

Fimalgoritmo