Algoritmo "Exercicio2"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 10/09/2026
Var
// Seção de Declarações das variáveis
acumulador, acrescimo:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
acumulador<-1
enquanto acumulador<101 faca
Escreval(acumulador, "+", acrescimo)
fimenquanto
acrescimo<- acumulador + acrescimo
Fimalgoritmo