Algoritmo "soma"
// Disciplina   : Lógica de Programação com JavaScript
// Professor   : Jailson
// Descrição   : Efetuar uma soma
// Autor(a)    : Larissa Fernandes Coelho
// Data atual  : 28/08/2026
Var
// Seção de Declarações das variáveis 
numero01:inteiro;
numero02:inteiro;
soma:inteiro;

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Escreval("Programa Soma")
Escreva("Digite o primeiro número: ")
leia(numero01)
Escreval("Digite o segundo número: ")
leia(numero02)
soma<-numero01+numero02
Escreval("A soma dos números dígitados é de: ", soma)


Fimalgoritmo