Algoritmo "Exercicio23"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 09/09/2026
Var
// Seção de Declarações das variáveis 
numero:real;

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Escreval("Descubra se o número é positivo ou negativo! ")
Escreval("Digite um número: ")
leia(numero)

se numero<0 entao
Escreval("O número é negativo. ")
senao
se numero >=0  entao
Escreval("O número é positivo. ")
senao
Escreval("O número é inválido. ")
fimse
fimse
Fimalgoritmo
