Algoritmo "EXERCICIO09"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 31/08/2026
Var
// Seção de Declarações das variáveis 
ladoQuadrado:real;
calculo:real;
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Escreval("Qual o valor de área do quadrado? ")
leia(ladoQuadrado)
calculo<-ladoQuadrado * ladoQuadrado
Escreval("O resultado do calculo da área do quadrado é de: ", calculo)

Fimalgoritmo