Algoritmo "Exercicio57"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 20/09/2026
Var
// Seção de Declarações das variáveis 
numero, i, resultado: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("Digite um numero: ")
leia(numero)

i <- 1

enquanto i <= 10 faca
resultado <- numero * i
escreval(numero, " x ", i, " = ", resultado)
i <- i + 1

Fimalgoritmo