Algoritmo " Exercicio06"
// Disciplina   : [Lógica de Programação com JavaScript]
// Professor   : Jailson
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 28/08/2026
Var
// Seção de Declarações das variáveis 
numero:inteiro;
sucessor:inteiro;

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Escreval("Digite um número e decubra o seu sucessor: ")
leia(numero)
sucessor<- numero+1
Escreva("O número sucessor é de: ", sucessor)

Fimalgoritmo