Algoritmo "ExercicioDoWhile"
// Disciplina   : [Lógica de Programação JS]
// Professor   : Antonio Carlos Nicolodi
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 10/09/2026
Var
   // Seção de Declarações das variáveis
   contadora: inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   repita
      escreval("Do while")
      contadora<-contadora +1
      ate contadora>10
Fimalgoritmo