Algoritmo "Exercicio61"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 22/09/2026
Var
// Seção de Declarações das variáveis 
expoente, i, potencia: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
expoente <- 0
enquanto expoente <= 15 faca

potencia <- 1
i <- 1

enquanto i <= expoente faca
potencia <- potencia * 3
i <- i + 1
fimenquanto

escreval("3 elevado a ", expoente, " = ", potencia)

expoente <- expoente + 1
fimenquanto

Fimalgoritmo