Algoritmo "ExercicioAulas01"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 02/09/2026
Var
   // Seção de Declarações das variáveis
   idade:inteiro;


Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   Escreva("Digite sua idade: ")
   leia(idade)

   se idade <18 entao
      Escreval("Você é menor de idade. ")
   senao Escreval("Você é maior de idade. ")
   fimse
Fimalgoritmo