Algoritmo "multiplicação"
// Disciplina   : [Lógica de Programação com JavaScript]
// Professor   : Jailson
// Descrição   : Efetua uma multiplicação
// Autor(a)    : Larissa Fernandes Coelho
// Data atual  : 28/08/2026
Var
// Seção de Declarações das variáveis 
numero01:inteiro
numero02:inteiro
resultado:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Escreval("Multiplique números ")
Escreva("Digite o primeiro número: ")
leia(numero01)
Escreva("Digite o primeiro número: ")
leia(numero02)
resultado<-numero01*numero02
Escreval("O resultado da multiplicação é de: ", resultado)


Fimalgoritmo