Algoritmo "Exercicio60"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 22/09/2026
Var
// Seção de Declarações das variáveis 
i: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
i <- 0
enquanto i <= 20 faca
se i mod 2 <> 0 entao
escreval(i)
fimse
i <- i + 1
fimenquanto


Fimalgoritmo